# -*- coding: utf-8 -*-
"""Actividad4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qWcVN9LTh0o-CcXs_dZ5VEmMEdsyUh9y
"""

import time

# RNG entre -1 y 1 utilizando la marca de tiempo en nanosegundos
def rng():
    tiempo_actual = time.time_ns()  # Obtener la marca de tiempo en nanosegundos
    numero_aleatorio = (tiempo_actual % 2001) / 1000.0 - 1  # Escalar entre -1 y 1
    return numero_aleatorio

# PRNG entre -100 y 100 utilizando una semilla personalizada
def prng(semilla):
    semilla = (semilla * 214013 + 2531011) & 0x7FFFFFFF  # Algoritmo de congruencia lineal
    numero_aleatorio = (semilla % 201) - 100  # Escalar entre -100 y 100
    return numero_aleatorio, semilla

# Ejemplo de uso
print(f"Número RNG entre -1 y 1: {rng()}")

# Inicializar semilla
semilla = time.time_ns() & 0xFFFFFFFF  # Tomamos una parte de la marca de tiempo como semilla

# Generar 5 números PRNG
for _ in range(5):
    numero, semilla = prng(semilla)
    print(f"Número PRNG entre -100 y 100: {numero}")