# -*- coding: utf-8 -*-
"""Actividad3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E8F9SLbndO1OBUq4c1IIl1L2P3Yf9ns0
"""

#Se importa la libreria random que permite generar números aleatorios
import random

# Se definen las clases con la distribución de estudiantes
distribucion_clases = {
    'Clase 1': {'A': 16, 'B': 4},
    'Clase 2': {'A': 14, 'B': 6},
    'Clase 3': {'A': 12, 'B': 8}
}

# Número total de estudiantes en cada clase
total_estudiantes_por_clase = 20

# ¿Cuál es la probabilidad de que el estudiante elegido sea del tipo B?
probabilidad_B = sum((clase['B'] / total_estudiantes_por_clase) * (1/3) for clase in distribucion_clases.values())

# (2) Calcular la probabilidad de que si un estudiante es tipo A, provenga de la Clase 1
# P(Clase 1 | A) = P(A | Clase 1) * P(Clase 1) / P(A)

# Probabilidad total de elegir un estudiante tipo A
probabilidad_A = sum((clase['A'] / total_estudiantes_por_clase) * (1/3) for clase in distribucion_clases.values())

# Probabilidad de elegir un estudiante tipo A dado que es de la Clase 1
prob_A_dado_Clase1 = distribucion_clases['Clase 1']['A'] / total_estudiantes_por_clase

# Probabilidad de elegir la Clase 1
prob_Clase1 = 1/3

# Probabilidad de que si un estudiante es A, provenga de la Clase 1
probabilidad_Clase1_dado_A = (prob_A_dado_Clase1 * prob_Clase1) / probabilidad_A

# Simulación del experimento
simulaciones = 100000
contador_B = 0
contador_Clase1_dado_A = 0

for _ in range(simulaciones):
    # Seleccionar una clase al azar
    clase_elegida = random.choice(list(distribucion_clases.keys()))

    # Seleccionar un estudiante aleatorio de esa clase
    estudiante_tipo = random.choices(['A', 'B'], weights=[distribucion_clases[clase_elegida]['A'],
                                                           distribucion_clases[clase_elegida]['B']])[0]

    # Contar cuántos son tipo B
    if estudiante_tipo == 'B':
        contador_B += 1

    # Contar si un estudiante tipo A proviene de la Clase 1
    if estudiante_tipo == 'A' and clase_elegida == 'Clase 1':
        contador_Clase1_dado_A += 1

# Probabilidades estimadas por simulación
probabilidad_B_simulada = contador_B / simulaciones
probabilidad_Clase1_dado_A_simulada = contador_Clase1_dado_A / (simulaciones * probabilidad_A)

# Imprimir los resultados
print(f"Probabilidad teórica de elegir un estudiante tipo B: {probabilidad_B:.4f}")
print(f"Probabilidad simulada de elegir un estudiante tipo B: {probabilidad_B_simulada:.4f}")
print(f"Probabilidad teórica de que un estudiante tipo A sea de la Clase 1: {probabilidad_Clase1_dado_A:.4f}")
print(f"Probabilidad simulada de que un estudiante tipo A sea de la Clase 1: {probabilidad_Clase1_dado_A_simulada:.4f}")